"""update shift table

Revision ID: 02e19aa9cae8
Revises: 36d5a17bfc2e
Create Date: 2025-11-20 12:10:33.041719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e19aa9cae8'
down_revision: Union[str, Sequence[str], None] = '36d5a17bfc2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('shifts', sa.Column('modified_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'modified_by')
    op.drop_column('shifts', 'created_by')
    # ### end Alembic commands ###
