"""create leave module tables

Revision ID: 05e9d936f3cc
Revises: 2277e8b40676
Create Date: 2025-12-19 18:43:13.265591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '05e9d936f3cc'
down_revision: Union[str, Sequence[str], None] = '2277e8b40676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_type', sa.String(length=100), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_types_id'), 'leave_types', ['id'], unique=False)
    op.create_table('test_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('failures', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_reports_id'), 'test_reports', ['id'], unique=False)
    op.create_table('leave_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('per_month', sa.Integer(), nullable=False),
    sa.Column('no_of_leaves', sa.Integer(), nullable=False),
    sa.Column('carry_forward', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_config_id'), 'leave_config', ['id'], unique=False)
    op.create_table('leave_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('leave_type_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('allocated', sa.Float(), nullable=False),
    sa.Column('used', sa.Float(), nullable=False),
    sa.Column('pending', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'leave_type_id', 'year', name='uq_leave_balance_user_type_year')
    )
    op.create_index('idx_leave_balance_user_year', 'leave_balances', ['user_id', 'year'], unique=False)
    op.create_index(op.f('ix_leave_balances_id'), 'leave_balances', ['id'], unique=False)
    op.alter_column('candidate_documents', 'candidate_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('candidate_documents', 'document_type',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('candidate_documents', 'document_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('candidates', 'job_posting_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('email'), table_name='candidates')
    op.add_column('job_postings', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('fk_job_postings_created_by'), 'job_postings', type_='foreignkey')
    op.drop_column('job_postings', 'created_by_id')
    op.drop_column('job_postings', 'created_by_name')
    op.add_column('leave_master', sa.Column('leave_type_id', sa.Integer(), nullable=False))
    op.add_column('leave_master', sa.Column('leave_days', sa.Float(), nullable=False))
    op.create_foreign_key(None, 'leave_master', 'leave_types', ['leave_type_id'], ['id'])
    op.drop_column('leave_master', 'balance')
    op.drop_column('leave_master', 'carry_forward')
    op.drop_column('leave_master', 'allocated')
    op.drop_column('leave_master', 'used')
    op.drop_column('leave_master', 'leave_type')
    op.add_column('notifications', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('notifications', 'message',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'notifications', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'message',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'created_by')
    op.add_column('leave_master', sa.Column('leave_type', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('leave_master', sa.Column('used', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leave_master', sa.Column('allocated', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leave_master', sa.Column('carry_forward', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('leave_master', sa.Column('balance', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'leave_master', type_='foreignkey')
    op.drop_column('leave_master', 'leave_days')
    op.drop_column('leave_master', 'leave_type_id')
    op.add_column('job_postings', sa.Column('created_by_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('job_postings', sa.Column('created_by_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_job_postings_created_by'), 'job_postings', 'users', ['created_by_id'], ['id'])
    op.drop_column('job_postings', 'created_by')
    op.create_index(op.f('email'), 'candidates', ['email'], unique=True)
    op.alter_column('candidates', 'job_posting_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('candidate_documents', 'document_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('candidate_documents', 'document_type',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('candidate_documents', 'candidate_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_leave_balances_id'), table_name='leave_balances')
    op.drop_index('idx_leave_balance_user_year', table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_index(op.f('ix_leave_config_id'), table_name='leave_config')
    op.drop_table('leave_config')
    op.drop_index(op.f('ix_test_reports_id'), table_name='test_reports')
    op.drop_table('test_reports')
    op.drop_index(op.f('ix_leave_types_id'), table_name='leave_types')
    op.drop_table('leave_types')
    # ### end Alembic commands ###
