"""add course_id to quiz_checkpoint and category_id to courses

Revision ID: 0f81e38f3df2
Revises: 8a0a0d248330
Create Date: 2025-10-06 15:59:24.694446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f81e38f3df2'
down_revision: Union[str, Sequence[str], None] = '8a0a0d248330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_checkpoints', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quiz_checkpoints', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_checkpoints', type_='foreignkey')
    op.drop_column('quiz_checkpoints', 'course_id')
    # ### end Alembic commands ###
