"""remove unused fields from candidate

Revision ID: 13d2d7cea878
Revises: af5c675b8756
Create Date: 2025-12-19 20:13:21.849426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13d2d7cea878'
down_revision: Union[str, Sequence[str], None] = 'af5c675b8756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'nationality')
    op.drop_column('candidates', 'address_line2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('address_line2', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('candidates', sa.Column('nationality', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
