"""create department table

Revision ID: 1401178fc969
Revises: d9b977eb5e42
Create Date: 2025-09-25 12:55:26.310218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1401178fc969'
down_revision: Union[str, Sequence[str], None] = 'd9b977eb5e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('permissions')
    op.drop_column('description')
    op.drop_column('created_at')
    op.drop_column('updated_at')
    op.drop_column('status')
    op.drop_column('code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(sa.Column('code', mysql.VARCHAR(length=20), nullable=False))
    op.add_column(sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column(sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))
    op.add_column(sa.Column('permissions', mysql.TEXT(), nullable=True))
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
