"""add anomaly_flag to Attendance

Revision ID: 14fe199f13ab
Revises: d1afc39f6407
Create Date: 2025-12-04 12:22:16.913720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '14fe199f13ab'
down_revision: Union[str, Sequence[str], None] = 'd1afc39f6407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('anomaly_flag', sa.String(length=20), nullable=True))
    op.drop_column('users', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    op.drop_column('attendances', 'anomaly_flag')
    # ### end Alembic commands ###
