"""initial migration

Revision ID: 1636d980013e
Revises: 
Create Date: 2025-11-26 15:55:12.874322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1636d980013e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflows')
    op.drop_table('job_roles')
    op.add_column('job_postings', sa.Column('job_description_id', sa.Integer(), nullable=False))
    op.add_column('job_postings', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('job_postings', sa.Column('created_by_name', sa.String(length=100), nullable=True))
    op.add_column('job_postings', sa.Column('approval_status', sa.Enum('pending', 'accepted', 'rejected', name='approvalstatus'), nullable=False))
    op.drop_constraint(op.f('job_postings_ibfk_2'), 'job_postings', type_='foreignkey')
    op.create_foreign_key(None, 'job_postings', 'job_descriptions', ['job_description_id'], ['id'])
    op.create_foreign_key(None, 'job_postings', 'users', ['created_by_id'], ['id'])
    op.drop_column('job_postings', 'job_role_id')
    op.drop_column('job_postings', 'created_by')
    op.alter_column('shifts', 'created_by',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Integer(),
               nullable=False)
    op.create_foreign_key(None, 'shifts', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shifts', type_='foreignkey')
    op.alter_column('shifts', 'created_by',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=100),
               nullable=True)
    op.add_column('job_postings', sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('job_postings', sa.Column('job_role_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.create_foreign_key(op.f('job_postings_ibfk_2'), 'job_postings', 'job_roles', ['job_role_id'], ['id'])
    op.drop_column('job_postings', 'approval_status')
    op.drop_column('job_postings', 'created_by_name')
    op.drop_column('job_postings', 'created_by_id')
    op.drop_column('job_postings', 'job_description_id')
    op.create_table('job_roles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('required_skills', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('modified_by', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('workflows',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('posting_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approval_status', mysql.ENUM('pending', 'accepted', 'rejected'), nullable=True),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], name=op.f('workflows_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
