"""create a leavemaster table

Revision ID: 171964148c4d
Revises: 58048e98ce77
Create Date: 2025-10-07 16:39:00.563471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171964148c4d'
down_revision: Union[str, Sequence[str], None] = '58048e98ce77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_master', sa.Column('leave_type', sa.Enum('CASUAL', 'SICK', 'EARNED', 'MATERNITY', 'BEREAVEMENT', 'STUDY', 'SPECIAL', 'UNPAID', 'PUBLIC_HOLIDAY', 'COMP_OFF', name='leavetypeenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_master', 'leave_type')
    # ### end Alembic commands ###
