"""add video_id and completed_at to quiz_histories

Revision ID: 1780098328a8
Revises: 02569c646f8f
Create Date: 2025-09-25 10:54:56.979869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1780098328a8'
down_revision: Union[str, Sequence[str], None] = '02569c646f8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_histories', sa.Column('video_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quiz_histories', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_histories', type_='foreignkey')
    op.drop_column('quiz_histories', 'video_id')
    # ### end Alembic commands ###
