"""added shift roster detail model

Revision ID: 192231a34845
Revises: 3b874b0ec581
Create Date: 2025-11-24 16:40:35.440789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192231a34845'
down_revision: Union[str, Sequence[str], None] = '3b874b0ec581'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_roster_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_roster_id', sa.Integer(), nullable=False),
    sa.Column('week_day_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['shift_roster_id'], ['shift_rosters.id'], ),
    sa.ForeignKeyConstraint(['week_day_id'], ['week_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_roster_details_id'), 'shift_roster_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_roster_details_id'), table_name='shift_roster_details')
    op.drop_table('shift_roster_details')
    # ### end Alembic commands ###
