"""added shift roster id in users model

Revision ID: 1aac06f04dc2
Revises: 192231a34845
Create Date: 2025-11-24 16:57:58.069841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aac06f04dc2'
down_revision: Union[str, Sequence[str], None] = '192231a34845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('shift_roster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'shift_rosters', ['shift_roster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'shift_roster_id')
    # ### end Alembic commands ###
