"""create a shift_roaster table

Revision ID: 1d67ef805ef8
Revises: 7c1d2a091745
Create Date: 2025-11-08 23:27:33.584654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d67ef805ef8'
down_revision: Union[str, Sequence[str], None] = '7c1d2a091745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_rosters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_shift_rosters_id'), 'shift_rosters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_rosters_id'), table_name='shift_rosters')
    op.drop_table('shift_rosters')
    # ### end Alembic commands ###
