"""Removed workflow from candidate

Revision ID: 1d9ac6d450da
Revises: 57cda309a51b
Create Date: 2025-11-20 15:02:55.226259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1d9ac6d450da'
down_revision: Union[str, Sequence[str], None] = '57cda309a51b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('candidates', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candidates', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('modified_by', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('candidates_ibfk_1'), 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'workflow_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('workflow_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('candidates_ibfk_1'), 'candidates', 'workflows', ['workflow_id'], ['id'])
    op.drop_column('candidates', 'modified_by')
    op.drop_column('candidates', 'created_by')
    op.drop_column('candidates', 'updated_at')
    op.drop_column('candidates', 'created_at')
    # ### end Alembic commands ###
