"""added holiday

Revision ID: 2277e8b40676
Revises: 55172c4efa98
Create Date: 2025-12-03 11:38:50.213965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2277e8b40676'
down_revision: Union[str, Sequence[str], None] = '55172c4efa98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_punches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bio_id', sa.String(length=120), nullable=False),
    sa.Column('punch_date', sa.Date(), nullable=False),
    sa.Column('punch_time', sa.Time(), nullable=False),
    sa.Column('punch_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_punches_id'), 'attendance_punches', ['id'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('modified_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=True)
    op.create_index(op.f('ix_holidays_id'), 'holidays', ['id'], unique=False)
    op.add_column('attendances', sa.Column('month', sa.Date(), nullable=False))
    op.add_column('attendances', sa.Column('total_days', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('present_days', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('absent_days', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('half_days', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('holidays', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('sundays', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('leaves', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('permissions', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('total_work_minutes', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('overtime_minutes', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('late_minutes', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('early_exit_minutes', sa.Integer(), nullable=True))
    op.add_column('attendances', sa.Column('summary_status', sa.String(length=30), nullable=True))
    op.alter_column('attendances', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.create_index(op.f('ix_attendances_month'), 'attendances', ['month'], unique=False)
    op.drop_constraint(op.f('attendances_ibfk_1'), 'attendances', type_='foreignkey')
    op.drop_column('attendances', 'attendance_date')
    op.drop_column('attendances', 'total_worked_minutes')
    op.drop_column('attendances', 'shift_id')
    op.drop_column('attendances', 'punch_in')
    op.drop_column('attendances', 'status')
    op.drop_column('attendances', 'punch_out')
    op.add_column('leave_master', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('leave_master', sa.Column('is_half_day', sa.Boolean(), nullable=True))
    op.drop_column('leave_master', 'description')
    op.drop_column('leave_master', 'holiday')
    op.add_column('permissions', sa.Column('from_time', sa.Time(), nullable=True))
    op.add_column('permissions', sa.Column('to_time', sa.Time(), nullable=True))
    op.add_column('users', sa.Column('salary_structure_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'salary_structures', ['salary_structure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'salary_structure_id')
    op.drop_column('permissions', 'to_time')
    op.drop_column('permissions', 'from_time')
    op.add_column('leave_master', sa.Column('holiday', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('leave_master', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('leave_master', 'is_half_day')
    op.drop_column('leave_master', 'status')
    op.add_column('attendances', sa.Column('punch_out', mysql.DATETIME(), nullable=False))
    op.add_column('attendances', sa.Column('status', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('attendances', sa.Column('punch_in', mysql.DATETIME(), nullable=False))
    op.add_column('attendances', sa.Column('shift_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('attendances', sa.Column('total_worked_minutes', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('attendances', sa.Column('attendance_date', sa.DATE(), nullable=False))
    op.create_foreign_key(op.f('attendances_ibfk_1'), 'attendances', 'shifts', ['shift_id'], ['id'])
    op.drop_index(op.f('ix_attendances_month'), table_name='attendances')
    op.alter_column('attendances', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.drop_column('attendances', 'summary_status')
    op.drop_column('attendances', 'early_exit_minutes')
    op.drop_column('attendances', 'late_minutes')
    op.drop_column('attendances', 'overtime_minutes')
    op.drop_column('attendances', 'total_work_minutes')
    op.drop_column('attendances', 'permissions')
    op.drop_column('attendances', 'leaves')
    op.drop_column('attendances', 'sundays')
    op.drop_column('attendances', 'holidays')
    op.drop_column('attendances', 'half_days')
    op.drop_column('attendances', 'absent_days')
    op.drop_column('attendances', 'present_days')
    op.drop_column('attendances', 'total_days')
    op.drop_column('attendances', 'month')
    op.drop_index(op.f('ix_holidays_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_attendance_punches_id'), table_name='attendance_punches')
    op.drop_table('attendance_punches')
    # ### end Alembic commands ###
