"""adding extra fields to shift table

Revision ID: 25c8d4d48431
Revises: 6280bfe58b28
Create Date: 2025-09-25 10:34:09.899276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c8d4d48431'
down_revision: Union[str, Sequence[str], None] = '6280bfe58b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('shift_code', sa.String(length=50), nullable=False))
    op.add_column('shifts', sa.Column('shift_name', sa.String(length=100), nullable=False))
    op.add_column('shifts', sa.Column('working_minutes', sa.Integer(), nullable=False))
    op.add_column('shifts', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('shifts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('shifts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'shifts', ['shift_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shifts', type_='unique')
    op.drop_column('shifts', 'updated_at')
    op.drop_column('shifts', 'created_at')
    op.drop_column('shifts', 'status')
    op.drop_column('shifts', 'working_minutes')
    op.drop_column('shifts', 'shift_name')
    op.drop_column('shifts', 'shift_code')
    # ### end Alembic commands ###
