"""fix organization-branch relationship

Revision ID: 2bb544b81e38
Revises: 5b2bafb247ee
Create Date: 2025-09-26 16:06:08.984644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2bb544b81e38'
down_revision: Union[str, Sequence[str], None] = '5b2bafb247ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_constraint(op.f('organizations_ibfk_1'), 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'updated_at')
    op.drop_column('organizations', 'created_at')
    op.drop_column('organizations', 'branch_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('branch_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('organizations', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.create_foreign_key(op.f('organizations_ibfk_1'), 'organizations', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    op.alter_column('organizations', 'description',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
