"""adding extra fields to job postings table

Revision ID: 31b2ce903193
Revises: 2277e8b40676
Create Date: 2025-12-08 16:20:22.302417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31b2ce903193'
down_revision: Union[str, Sequence[str], None] = '2277e8b40676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidate_documents', 'candidate_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('candidate_documents', 'document_type',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('candidate_documents', 'document_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.add_column('candidates', sa.Column('candidate_type', sa.String(length=20), nullable=False))
    op.add_column('candidates', sa.Column('highest_qualification', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('college_name', sa.String(length=150), nullable=True))
    op.add_column('candidates', sa.Column('graduation_year', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('course', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('cgpa', sa.String(length=10), nullable=True))
    op.add_column('candidates', sa.Column('total_experience', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('previous_company', sa.String(length=150), nullable=True))
    op.add_column('candidates', sa.Column('last_ctc', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('telugu_level', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('english_level', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('hindi_level', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('candidates', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('candidates', sa.Column('nationality', sa.String(length=50), nullable=True))
    op.add_column('candidates', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('candidates', sa.Column('pincode', sa.String(length=20), nullable=True))
    op.alter_column('candidates', 'job_posting_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('email'), table_name='candidates')
    op.add_column('job_postings', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.add_column('job_postings', sa.Column('job_type', sa.Enum('fresher', 'experienced', 'both', name='jobtype'), nullable=False))
    op.add_column('job_postings', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('fk_job_postings_created_by'), 'job_postings', type_='foreignkey')
    op.create_foreign_key(None, 'job_postings', 'organizations', ['organization_id'], ['id'])
    op.drop_column('job_postings', 'created_by_id')
    op.drop_column('job_postings', 'created_by_name')
    op.add_column('notifications', sa.Column('created_by', sa.Integer(), nullable=False))
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('notifications', 'message',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'notifications', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.alter_column('notifications', 'message',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('notifications', 'created_at')
    op.drop_column('notifications', 'is_read')
    op.drop_column('notifications', 'created_by')
    op.add_column('job_postings', sa.Column('created_by_name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('job_postings', sa.Column('created_by_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_job_postings_created_by'), 'job_postings', 'users', ['created_by_id'], ['id'])
    op.drop_column('job_postings', 'created_by')
    op.drop_column('job_postings', 'job_type')
    op.drop_column('job_postings', 'organization_id')
    op.create_index(op.f('email'), 'candidates', ['email'], unique=True)
    op.alter_column('candidates', 'job_posting_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('candidates', 'pincode')
    op.drop_column('candidates', 'country')
    op.drop_column('candidates', 'state')
    op.drop_column('candidates', 'city')
    op.drop_column('candidates', 'address_line2')
    op.drop_column('candidates', 'address_line1')
    op.drop_column('candidates', 'nationality')
    op.drop_column('candidates', 'date_of_birth')
    op.drop_column('candidates', 'gender')
    op.drop_column('candidates', 'hindi_level')
    op.drop_column('candidates', 'english_level')
    op.drop_column('candidates', 'telugu_level')
    op.drop_column('candidates', 'last_ctc')
    op.drop_column('candidates', 'previous_company')
    op.drop_column('candidates', 'total_experience')
    op.drop_column('candidates', 'cgpa')
    op.drop_column('candidates', 'course')
    op.drop_column('candidates', 'graduation_year')
    op.drop_column('candidates', 'college_name')
    op.drop_column('candidates', 'skills')
    op.drop_column('candidates', 'highest_qualification')
    op.drop_column('candidates', 'candidate_type')
    op.alter_column('candidate_documents', 'document_url',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('candidate_documents', 'document_type',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('candidate_documents', 'candidate_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
