"""create a shift_change_request table

Revision ID: 31e074d24f40
Revises: 45b03626a21d
Create Date: 2025-10-29 17:44:29.652829
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31e074d24f40'
down_revision: Union[str, Sequence[str], None] = '45b03626a21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create shift_change_requests table only
    op.create_table(
        'shift_change_requests',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('old_shift_id', sa.Integer(), sa.ForeignKey('shifts.id'), nullable=True),
        sa.Column('new_shift_id', sa.Integer(), sa.ForeignKey('shifts.id'), nullable=False),
        sa.Column('request_date', sa.Date(), nullable=False),
        sa.Column('reason', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True)
    )
    op.create_index(op.f('ix_shift_change_requests_id'), 'shift_change_requests', ['id'], unique=False)

    # --- Column alterations / indexes (from autogenerated) ---
    op.alter_column('candidate_documents', 'document_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('candidate_documents', 'document_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('candidates', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('candidates', 'phone_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('candidates', 'resume_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_unique_constraint(None, 'candidates', ['email'])

    # Continue other alterations as needed (job_postings, leave_master, shifts, users, workflows...)
    # You can keep the rest of your column/index changes here as in your original migration
    # Just make sure NOT to recreate 'attendances'

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_shift_change_requests_id'), table_name='shift_change_requests')
    op.drop_table('shift_change_requests')
    
    # Reverse other alterations if necessary
