"""Added formula table

Revision ID: 32237f15997d
Revises: b1865ac8155a
Create Date: 2025-10-13 11:36:02.368181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32237f15997d'
down_revision: Union[str, Sequence[str], None] = 'b1865ac8155a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_code', sa.String(length=50), nullable=False),
    sa.Column('component_name', sa.String(length=100), nullable=False),
    sa.Column('formula_text', sa.String(length=255), nullable=False),
    sa.Column('formula_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('component_code')
    )
    op.create_index(op.f('ix_formulas_id'), 'formulas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formulas_id'), table_name='formulas')
    op.drop_table('formulas')
    # ### end Alembic commands ###
