"""fix varchar length for payroll attendance

Revision ID: 3293ac269643
Revises: dc8c7d8f36ef
Create Date: 2025-11-06 14:41:49.347386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3293ac269643'
down_revision: Union[str, Sequence[str], None] = 'dc8c7d8f36ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=10), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=True),
    sa.Column('present_days', sa.Integer(), nullable=True),
    sa.Column('half_days', sa.Integer(), nullable=True),
    sa.Column('absent_days', sa.Integer(), nullable=True),
    sa.Column('gross_salary', sa.Float(), nullable=True),
    sa.Column('net_salary', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('generated_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_attendance_id'), 'payroll_attendance', ['id'], unique=False)
    op.alter_column('attendances', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('attendances_ibfk_2'), 'attendances', type_='foreignkey')
    op.drop_constraint(op.f('attendances_ibfk_1'), 'attendances', type_='foreignkey')
    op.create_foreign_key(None, 'attendances', 'shifts', ['shift_id'], ['id'])
    op.create_foreign_key(None, 'attendances', 'users', ['user_id'], ['id'])
    op.drop_column('attendances', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.create_foreign_key(op.f('attendances_ibfk_1'), 'attendances', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('attendances_ibfk_2'), 'attendances', 'shifts', ['shift_id'], ['id'], ondelete='CASCADE')
    op.alter_column('attendances', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_payroll_attendance_id'), table_name='payroll_attendance')
    op.drop_table('payroll_attendance')
    # ### end Alembic commands ###
