"""update departmrnt add audit files

Revision ID: 348ae3352a93
Revises: da2dc319f17c
Create Date: 2025-11-21 15:37:32.342524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '348ae3352a93'
down_revision: Union[str, Sequence[str], None] = 'da2dc319f17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('departments', sa.Column('modified_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'modified_by')
    op.drop_column('departments', 'created_by')
    # ### end Alembic commands ###
