"""create department table

Revision ID: 35a15b1ce4e4
Revises: 1401178fc969
Create Date: 2025-09-25 13:10:12.317194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '35a15b1ce4e4'
down_revision: Union[str, Sequence[str], None] = '1401178fc969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'status')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'description')
    op.drop_column('roles', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('code', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('roles', sa.Column('description', mysql.TEXT(), nullable=True))
    op.add_column('roles', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('roles', sa.Column('permissions', mysql.TEXT(), nullable=True))
    op.add_column('roles', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('roles', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
