"""modified user table

Revision ID: 36d5a17bfc2e
Revises: b098e3f1926d
Create Date: 2025-11-20 11:58:12.649134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d5a17bfc2e'
down_revision: Union[str, Sequence[str], None] = 'b098e3f1926d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('modified_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'modified_by')
    op.drop_column('users', 'created_by')
    # ### end Alembic commands ###
