"""Add shift_name to shifts table

Revision ID: 36e00fa88c45
Revises: 57187500bb55
Create Date: 2025-11-11 17:26:41.494073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '36e00fa88c45'
down_revision: Union[str, Sequence[str], None] = '57187500bb55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('name'), table_name='shifts')
    op.drop_index(op.f('name_2'), table_name='shifts')
    op.drop_index(op.f('uq_shifts_name'), table_name='shifts')
    op.drop_column('shifts', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('uq_shifts_name'), 'shifts', ['name'], unique=True)
    op.create_index(op.f('name_2'), 'shifts', ['name'], unique=True)
    op.create_index(op.f('name'), 'shifts', ['name'], unique=True)
    # ### end Alembic commands ###
