"""added weekday model

Revision ID: 3b874b0ec581
Revises: 4a9c3ffc5146
Create Date: 2025-11-24 16:38:43.891245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b874b0ec581'
down_revision: Union[str, Sequence[str], None] = '4a9c3ffc5146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_name', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_name')
    )
    op.create_index(op.f('ix_week_days_id'), 'week_days', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_week_days_id'), table_name='week_days')
    op.drop_table('week_days')
    # ### end Alembic commands ###
