"""Add course_id to quiz_histories

Revision ID: 3cf1aaa5469a
Revises: e641630bcf5c
Create Date: 2025-09-09 17:40:40.291133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3cf1aaa5469a'
down_revision: Union[str, Sequence[str], None] = 'e641630bcf5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_histories', sa.Column('course_id', sa.Integer(), nullable=False))
    op.alter_column('quiz_histories', 'answer',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('quiz_histories', 'result',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.create_foreign_key(None, 'quiz_histories', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz_histories', type_='foreignkey')
    op.alter_column('quiz_histories', 'result',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('quiz_histories', 'answer',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    op.drop_column('quiz_histories', 'course_id')
    # ### end Alembic commands ###
