"""Added formula_text column to formulas

Revision ID: 3dbaf8673fa1
Revises: 46a898423a5d
Create Date: 2025-10-13 17:46:44.016817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3dbaf8673fa1'
down_revision: Union[str, Sequence[str], None] = '46a898423a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulas', sa.Column('formula_text', sa.String(length=255), nullable=False))
    op.add_column('formulas', sa.Column('formula_type', sa.String(length=50), nullable=True))
    op.add_column('formulas', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('formulas', 'formula_expression')
    op.drop_column('formulas', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulas', sa.Column('category', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('formulas', sa.Column('formula_expression', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('formulas', 'description')
    op.drop_column('formulas', 'formula_type')
    op.drop_column('formulas', 'formula_text')
    # ### end Alembic commands ###
