"""create a user table

Revision ID: 40e4b4b2f46b
Revises: 3d1e1830c341
Create Date: 2025-11-08 20:40:03.858162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '40e4b4b2f46b'
down_revision: Union[str, Sequence[str], None] = '3d1e1830c341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('component_code'), table_name='formulas')
    op.drop_index(op.f('ix_formulas_id'), table_name='formulas')
    op.drop_table('formulas')
    op.drop_index(op.f('ix_salary_structures_id'), table_name='salary_structures')
    op.drop_table('salary_structures')
    op.drop_index(op.f('ix_payrolls_id'), table_name='payrolls')
    op.drop_table('payrolls')
    op.add_column('attendances', sa.Column('punch_id', sa.String(length=100), nullable=False))
    op.add_column('attendances', sa.Column('first_punch', sa.DateTime(), nullable=True))
    op.add_column('attendances', sa.Column('last_punch', sa.DateTime(), nullable=True))
    op.add_column('attendances', sa.Column('shift_start', sa.DateTime(), nullable=True))
    op.add_column('attendances', sa.Column('shift_end', sa.DateTime(), nullable=True))
    op.add_column('attendances', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('attendances', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('attendances', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('attendances', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.drop_constraint(op.f('attendances_ibfk_1'), 'attendances', type_='foreignkey')
    op.drop_column('attendances', 'total_worked_minutes')
    op.drop_column('attendances', 'shift_id')
    op.drop_column('attendances', 'punch_in')
    op.drop_column('attendances', 'punch_out')
    op.drop_constraint(op.f('quiz_checkpoints_ibfk_2'), 'quiz_checkpoints', type_='foreignkey')
    op.drop_column('quiz_checkpoints', 'course_id')
    op.drop_constraint(op.f('quiz_histories_ibfk_4'), 'quiz_histories', type_='foreignkey')
    op.drop_column('quiz_histories', 'video_id')
    op.drop_column('quiz_histories', 'completed_at')
    op.add_column('shifts', sa.Column('is_rotational', sa.Boolean(), nullable=True))
    op.alter_column('shifts', 'start_time',
               existing_type=mysql.TIME(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('shifts', 'end_time',
               existing_type=mysql.TIME(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('shifts', 'shift_code',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('name'), table_name='shifts')
    op.drop_column('shifts', 'name')
    op.drop_column('shifts', 'shift_name')
    op.drop_column('shifts', 'description')
    op.drop_column('shifts', 'lag_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('lag_minutes', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('shifts', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('shifts', sa.Column('shift_name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('shifts', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('name'), 'shifts', ['name'], unique=True)
    op.alter_column('shifts', 'shift_code',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('shifts', 'end_time',
               existing_type=sa.String(length=10),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.alter_column('shifts', 'start_time',
               existing_type=sa.String(length=10),
               type_=mysql.TIME(),
               existing_nullable=False)
    op.drop_column('shifts', 'is_rotational')
    op.add_column('quiz_histories', sa.Column('completed_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.add_column('quiz_histories', sa.Column('video_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('quiz_histories_ibfk_4'), 'quiz_histories', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.add_column('quiz_checkpoints', sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('quiz_checkpoints_ibfk_2'), 'quiz_checkpoints', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.add_column('attendances', sa.Column('punch_out', mysql.DATETIME(), nullable=False))
    op.add_column('attendances', sa.Column('punch_in', mysql.DATETIME(), nullable=False))
    op.add_column('attendances', sa.Column('shift_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('attendances', sa.Column('total_worked_minutes', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('attendances_ibfk_1'), 'attendances', 'shifts', ['shift_id'], ['id'])
    op.alter_column('attendances', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_column('attendances', 'updated_at')
    op.drop_column('attendances', 'longitude')
    op.drop_column('attendances', 'latitude')
    op.drop_column('attendances', 'shift_end')
    op.drop_column('attendances', 'shift_start')
    op.drop_column('attendances', 'last_punch')
    op.drop_column('attendances', 'first_punch')
    op.drop_column('attendances', 'punch_id')
    op.create_table('payrolls',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('salary_structure_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', mysql.VARCHAR(length=7), nullable=False),
    sa.Column('basic_salary', mysql.FLOAT(), nullable=False),
    sa.Column('allowances', mysql.FLOAT(), nullable=True),
    sa.Column('deductions', mysql.FLOAT(), nullable=True),
    sa.Column('bonus', mysql.FLOAT(), nullable=True),
    sa.Column('gross_salary', mysql.FLOAT(), nullable=True),
    sa.Column('net_salary', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], name=op.f('payrolls_ibfk_2'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('payrolls_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_payrolls_id'), 'payrolls', ['id'], unique=False)
    op.create_table('salary_structures',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('basic_salary_annual', mysql.FLOAT(), nullable=False),
    sa.Column('allowances_annual', mysql.FLOAT(), nullable=True),
    sa.Column('deductions_annual', mysql.FLOAT(), nullable=True),
    sa.Column('bonus_annual', mysql.FLOAT(), nullable=True),
    sa.Column('total_annual', mysql.FLOAT(), nullable=True),
    sa.Column('effective_from', sa.DATE(), nullable=False),
    sa.Column('effective_to', sa.DATE(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='salary_structures_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_salary_structures_id'), 'salary_structures', ['id'], unique=False)
    op.create_table('formulas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('component_code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('component_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('formula_expression', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('formula_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('salary_structure_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], name=op.f('formulas_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_formulas_id'), 'formulas', ['id'], unique=False)
    op.create_index(op.f('component_code'), 'formulas', ['component_code'], unique=True)
    op.create_table('permissions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shift_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('reason', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('permissions_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('permissions_ibfk_2'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    # ### end Alembic commands ###
