"""Add foreign key between SalaryStructure and Formula

Revision ID: 46a898423a5d
Revises: 32237f15997d
Create Date: 2025-10-13 17:03:40.231747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '46a898423a5d'
down_revision: Union[str, Sequence[str], None] = '32237f15997d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulas', sa.Column('formula_expression', sa.String(length=255), nullable=False))
    op.add_column('formulas', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('formulas', sa.Column('salary_structure_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'formulas', 'salary_structures', ['salary_structure_id'], ['id'], ondelete='CASCADE')
    op.drop_column('formulas', 'description')
    op.drop_column('formulas', 'formula_text')
    op.drop_column('formulas', 'formula_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formulas', sa.Column('formula_type', mysql.VARCHAR(length=20), nullable=True))
    op.add_column('formulas', sa.Column('formula_text', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('formulas', sa.Column('description', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'formulas', type_='foreignkey')
    op.drop_column('formulas', 'salary_structure_id')
    op.drop_column('formulas', 'category')
    op.drop_column('formulas', 'formula_expression')
    # ### end Alembic commands ###
