"""init clean schema

Revision ID: 46b6d6329fdf
Revises: 
Create Date: 2025-11-08 12:34:09.041675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '46b6d6329fdf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('punch_in', sa.DateTime(), nullable=False),
    sa.Column('punch_out', sa.DateTime(), nullable=False),
    sa.Column('total_worked_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.add_column('quiz_checkpoints', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quiz_checkpoints', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.add_column('quiz_histories', sa.Column('video_id', sa.Integer(), nullable=False))
    op.add_column('quiz_histories', sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'quiz_histories', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.add_column('shifts', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('shifts', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('shifts', sa.Column('shift_name', sa.String(length=100), nullable=False))
    op.add_column('shifts', sa.Column('lag_minutes', sa.Integer(), nullable=False))
    op.alter_column('shifts', 'start_time',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('shifts', 'end_time',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('shifts', 'shift_code',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_unique_constraint(None, 'shifts', ['name'])
    op.drop_column('shifts', 'is_rotational')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('is_rotational', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shifts', type_='unique')
    op.alter_column('shifts', 'shift_code',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('shifts', 'end_time',
               existing_type=sa.Time(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('shifts', 'start_time',
               existing_type=sa.Time(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('shifts', 'lag_minutes')
    op.drop_column('shifts', 'shift_name')
    op.drop_column('shifts', 'description')
    op.drop_column('shifts', 'name')
    op.drop_constraint(None, 'quiz_histories', type_='foreignkey')
    op.drop_column('quiz_histories', 'completed_at')
    op.drop_column('quiz_histories', 'video_id')
    op.drop_constraint(None, 'quiz_checkpoints', type_='foreignkey')
    op.drop_column('quiz_checkpoints', 'course_id')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_table('attendances')
    # ### end Alembic commands ###
