"""create candidates documents table

Revision ID: 4e321e6103bd
Revises: 49eddf5c0ff3
Create Date: 2025-10-29 12:21:01.736347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4e321e6103bd'
down_revision: Union[str, Sequence[str], None] = '49eddf5c0ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_shifts_id'), table_name='user_shifts')
    op.drop_table('user_shifts')
    op.alter_column('candidate_documents', 'document_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('candidate_documents', 'document_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('candidates', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('candidates', 'phone_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('candidates', 'resume_url',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_unique_constraint(None, 'candidates', ['email'])
    op.alter_column('job_postings', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('job_postings', 'number_of_positions',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('job_postings', 'employment_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('job_postings', 'location',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('job_postings', 'salary',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('job_postings', 'posting_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('job_postings', 'closing_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('job_postings', 'description_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('job_postings', 'created_by_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('job_postings_ibfk_1'), 'job_postings', type_='foreignkey')
    op.drop_constraint(op.f('job_postings_ibfk_2'), 'job_postings', type_='foreignkey')
    op.create_foreign_key(None, 'job_postings', 'roles', ['role_id'], ['id'])
    op.alter_column('job_roles', 'required_skills',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_job_roles_id'), 'job_roles', ['id'], unique=False)
    op.add_column('leave_master', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('leave_master', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('leave_master', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('leave_master', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_column('leave_master', 'start_date')
    op.drop_column('leave_master', 'end_date')
    op.drop_column('leave_master', 'leave_type')
    op.drop_constraint(op.f('quiz_checkpoints_ibfk_2'), 'quiz_checkpoints', type_='foreignkey')
    op.drop_column('quiz_checkpoints', 'course_id')
    op.add_column('shifts', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('shifts', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('shifts', sa.Column('shift_name', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'shifts', ['name'])
    op.drop_column('shifts', 'is_rotational')
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_index(op.f('biometric_id'), table_name='users')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'biometric_id')
    op.alter_column('workflows', 'approval_status',
               existing_type=mysql.ENUM('Pending', 'Approved', 'Rejected'),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'approval_status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('Pending', 'Approved', 'Rejected'),
               existing_nullable=True)
    op.add_column('users', sa.Column('biometric_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('biometric_id'), 'users', ['biometric_id'], unique=True)
    op.drop_column('users', 'name')
    op.add_column('shifts', sa.Column('is_rotational', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shifts', type_='unique')
    op.drop_column('shifts', 'shift_name')
    op.drop_column('shifts', 'description')
    op.drop_column('shifts', 'name')
    op.add_column('quiz_checkpoints', sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('quiz_checkpoints_ibfk_2'), 'quiz_checkpoints', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.add_column('leave_master', sa.Column('leave_type', mysql.ENUM('CASUAL', 'SICK', 'EARNED', 'MATERNITY', 'BEREAVEMENT', 'STUDY', 'SPECIAL', 'UNPAID', 'PUBLIC_HOLIDAY', 'COMP_OFF'), nullable=False))
    op.add_column('leave_master', sa.Column('end_date', sa.DATE(), nullable=False))
    op.add_column('leave_master', sa.Column('start_date', sa.DATE(), nullable=False))
    op.drop_column('leave_master', 'year')
    op.drop_column('leave_master', 'date')
    op.drop_column('leave_master', 'status')
    op.drop_column('leave_master', 'name')
    op.drop_index(op.f('ix_job_roles_id'), table_name='job_roles')
    op.alter_column('job_roles', 'required_skills',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.create_foreign_key(op.f('job_postings_ibfk_2'), 'job_postings', 'job_roles', ['description_id'], ['id'])
    op.create_foreign_key(op.f('job_postings_ibfk_1'), 'job_postings', 'job_roles', ['role_id'], ['id'])
    op.alter_column('job_postings', 'created_by_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('job_postings', 'description_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('job_postings', 'closing_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('job_postings', 'posting_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('job_postings', 'salary',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('job_postings', 'location',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('job_postings', 'employment_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('job_postings', 'number_of_positions',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('job_postings', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'candidates', type_='unique')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.alter_column('candidates', 'resume_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('candidates', 'phone_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('candidates', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('candidate_documents', 'document_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('candidate_documents', 'document_type',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.create_table('user_shifts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shift_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_date', sa.DATE(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('user_shifts_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_shifts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_shifts_id'), 'user_shifts', ['id'], unique=False)
    # ### end Alembic commands ###
