"""modified candidate doc

Revision ID: 57cda309a51b
Revises: b70718047e0b
Create Date: 2025-11-20 14:43:39.998710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57cda309a51b'
down_revision: Union[str, Sequence[str], None] = 'b70718047e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_documents', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('candidate_documents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('candidate_documents', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('candidate_documents', sa.Column('modified_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate_documents', 'modified_by')
    op.drop_column('candidate_documents', 'created_by')
    op.drop_column('candidate_documents', 'updated_at')
    op.drop_column('candidate_documents', 'created_at')
    # ### end Alembic commands ###
