"""Add branch_id to organization

Revision ID: 5b2bafb247ee
Revises: 61881ae6be24
Create Date: 2025-09-26 15:42:19.595063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2bafb247ee'
down_revision: Union[str, Sequence[str], None] = '61881ae6be24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'organizations', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'branch_id')
    # ### end Alembic commands ###
