"""Add lag_minutes column to shifts

Revision ID: 5bcc9b263b2c
Revises: 8f9d3c2b2703
Create Date: 2025-11-05 12:10:20.713314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bcc9b263b2c'
down_revision: Union[str, Sequence[str], None] = '8f9d3c2b2703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('lag_minutes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'lag_minutes')
    # ### end Alembic commands ###
