"""adding a s3_key field to video table

Revision ID: 5f15fee0bd76
Revises: 210936bc6ca5
Create Date: 2025-11-05 16:37:56.608131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5f15fee0bd76'
down_revision: Union[str, Sequence[str], None] = '210936bc6ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shift_logs_id'), table_name='shift_logs')
    op.drop_table('shift_logs')
    op.add_column('attendances', sa.Column('shift_start', sa.DateTime(), nullable=True))
    op.add_column('attendances', sa.Column('shift_end', sa.DateTime(), nullable=True))
    op.add_column('attendances', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('attendances', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('attendances', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('attendances', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('attendances', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('attendances_ibfk_2'), 'attendances', type_='foreignkey')
    op.drop_column('attendances', 'shift_id')
    op.drop_column('shifts', 'name')
    op.add_column('videos', sa.Column('s3_key', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 's3_key')
    op.add_column('shifts', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('attendances', sa.Column('shift_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('attendances_ibfk_2'), 'attendances', 'shifts', ['shift_id'], ['id'])
    op.drop_column('attendances', 'updated_at')
    op.drop_column('attendances', 'created_at')
    op.drop_column('attendances', 'status')
    op.drop_column('attendances', 'longitude')
    op.drop_column('attendances', 'latitude')
    op.drop_column('attendances', 'shift_end')
    op.drop_column('attendances', 'shift_start')
    op.create_table('shift_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('attendance_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shift_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('punch_time', mysql.DATETIME(), nullable=False),
    sa.Column('punch_type', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], name=op.f('shift_logs_ibfk_1')),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('shift_logs_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_shift_logs_id'), 'shift_logs', ['id'], unique=False)
    # ### end Alembic commands ###
