"""add branch_id to courses

Revision ID: 61881ae6be24
Revises: 744af3d0edbd
Create Date: 2025-09-26 15:35:11.863416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61881ae6be24'
down_revision: Union[str, Sequence[str], None] = '744af3d0edbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'branch_id')
    # ### end Alembic commands ###
