"""Add organizations table

Revision ID: 6393f452ce0f
Revises: ea07d98b8829
Create Date: 2025-09-25 13:03:31.425524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6393f452ce0f'
down_revision: Union[str, Sequence[str], None] = 'ea07d98b8829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.add_column('courses', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.alter_column('videos', 'title',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('videos', 'duration',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'duration',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('videos', 'title',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'organization_id')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
