"""add audit fields to leave_master

Revision ID: 6753a841fb47
Revises: 38eb9d4ee3b7
Create Date: 2025-11-20 17:20:44.917653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6753a841fb47'
down_revision: Union[str, Sequence[str], None] = '38eb9d4ee3b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_master', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('leave_master', sa.Column('modified_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leave_master', 'modified_by')
    op.drop_column('leave_master', 'created_by')
    # ### end Alembic commands ###
