"""remove organization_logo to orgnizations table

Revision ID: 7778a910a27e
Revises: df03ecb118cf
Create Date: 2025-11-28 17:14:33.682610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7778a910a27e'
down_revision: Union[str, Sequence[str], None] = 'df03ecb118cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
