"""Add branch_id to courses

Revision ID: 7ab10b23c15e
Revises: b27f9c55d94b
Create Date: 2025-10-04 16:03:41.518719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7ab10b23c15e'
down_revision: Union[str, Sequence[str], None] = 'b27f9c55d94b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branches', 'name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('branches', 'address',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.alter_column('branches', 'organization_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('name'), table_name='branches')
    op.add_column('courses', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'branch_id')
    op.create_index(op.f('name'), 'branches', ['name'], unique=True)
    op.alter_column('branches', 'organization_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('branches', 'address',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('branches', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
