"""updated job role

Revision ID: 7b56a030a5c5
Revises: 1d9ac6d450da
Create Date: 2025-11-20 16:32:54.565131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b56a030a5c5'
down_revision: Union[str, Sequence[str], None] = '1d9ac6d450da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_roles', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('job_roles', sa.Column('modified_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_roles', 'modified_by')
    op.drop_column('job_roles', 'created_by')
    # ### end Alembic commands ###
