"""create a week_master table

Revision ID: 7c1d2a091745
Revises: 94592c830e7e
Create Date: 2025-11-08 20:52:43.921139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7c1d2a091745'
down_revision: Union[str, Sequence[str], None] = '94592c830e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week_days', sa.Column('week_name', sa.String(length=20), nullable=False))
    op.drop_index(op.f('name'), table_name='week_days')
    op.create_unique_constraint(None, 'week_days', ['week_name'])
    op.drop_column('week_days', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('week_days', sa.Column('name', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'week_days', type_='unique')
    op.create_index(op.f('name'), 'week_days', ['name'], unique=True)
    op.drop_column('week_days', 'week_name')
    # ### end Alembic commands ###
