"""Add choices and correct_answer to quiz_checkpoints

Revision ID: 7ec27f156e30
Revises: b0aa6bb54999
Create Date: 2025-09-10 12:17:51.143658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec27f156e30'
down_revision: Union[str, Sequence[str], None] = 'b0aa6bb54999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
