"""Add question column to quiz_histories

Revision ID: 83ce9d12b7b2
Revises: f3b49cbd1504
Create Date: 2025-09-11 11:42:01.743967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ce9d12b7b2'
down_revision: Union[str, Sequence[str], None] = 'f3b49cbd1504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
