"""updated 4 models

Revision ID: 892ac80f3288
Revises: 63c53e670480
Create Date: 2025-11-17 16:26:11.474479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '892ac80f3288'
down_revision: Union[str, Sequence[str], None] = '63c53e670480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.add_column('candidates', sa.Column('job_posting_id', sa.Integer(), nullable=False))
    op.add_column('candidates', sa.Column('status', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'candidates', 'job_postings', ['job_posting_id'], ['id'])
    op.add_column('job_postings', sa.Column('job_role_id', sa.Integer(), nullable=False))
    op.alter_column('job_postings', 'number_of_positions',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('job_postings', 'employment_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('job_postings', 'location',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('job_postings', 'posting_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('job_postings', 'created_by_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('job_postings_ibfk_2'), 'job_postings', type_='foreignkey')
    op.create_foreign_key(None, 'job_postings', 'job_roles', ['job_role_id'], ['id'])
    op.drop_column('job_postings', 'description_id')
    op.drop_column('job_postings', 'role_id')
    op.alter_column('workflows', 'approval_status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('pending', 'accepted', 'rejected', name='approvalstatus'),
               existing_nullable=True)
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_constraint(op.f('workflows_ibfk_1'), 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'approver_id')
    op.drop_column('workflows', 'approval_required')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('approval_required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('workflows', sa.Column('approver_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('workflows_ibfk_1'), 'workflows', 'users', ['approver_id'], ['id'])
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.alter_column('workflows', 'approval_status',
               existing_type=sa.Enum('pending', 'accepted', 'rejected', name='approvalstatus'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
    op.add_column('job_postings', sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_postings', sa.Column('description_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.create_foreign_key(op.f('job_postings_ibfk_2'), 'job_postings', 'roles', ['role_id'], ['id'])
    op.alter_column('job_postings', 'created_by_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('job_postings', 'posting_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('job_postings', 'location',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('job_postings', 'employment_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('job_postings', 'number_of_positions',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('job_postings', 'job_role_id')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'status')
    op.drop_column('candidates', 'job_posting_id')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
