"""add category_id to courses

Revision ID: 8a0a0d248330
Revises: 7ab10b23c15e
Create Date: 2025-10-04 16:16:58.823907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0a0d248330'
down_revision: Union[str, Sequence[str], None] = '7ab10b23c15e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'category_id')
    # ### end Alembic commands ###
