"""add shift relation to permissions

Revision ID: 8f9d3c2b2703
Revises: 602426e31af6
Create Date: 2025-10-31 16:32:42.647700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8f9d3c2b2703'
down_revision: Union[str, Sequence[str], None] = '602426e31af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('shift_id', sa.Integer(), nullable=False))
    op.add_column('permissions', sa.Column('status', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'permissions', 'shifts', ['shift_id'], ['id'], ondelete='CASCADE')
    op.drop_column('permissions', 'permission_type')
    op.drop_column('permissions', 'end_time')
    op.drop_column('permissions', 'duration_minutes')
    op.drop_column('permissions', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('start_time', mysql.TIME(), nullable=False))
    op.add_column('permissions', sa.Column('duration_minutes', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('permissions', sa.Column('end_time', mysql.TIME(), nullable=False))
    op.add_column('permissions', sa.Column('permission_type', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'status')
    op.drop_column('permissions', 'shift_id')
    # ### end Alembic commands ###
