"""initial migration

Revision ID: 9360c83cbcd4
Revises: 
Create Date: 2025-10-29 10:02:28.698842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9360c83cbcd4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_roles_id'), table_name='job_roles')
    op.drop_index(op.f('title'), table_name='job_roles')
    op.drop_table('job_roles')
    op.drop_index(op.f('ix_user_shifts_id'), table_name='user_shifts')
    op.drop_table('user_shifts')
    op.drop_index(op.f('ix_workflows_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('email'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_candidate_documents_id'), table_name='candidate_documents')
    op.drop_table('candidate_documents')
    op.drop_index(op.f('ix_shift_change_requests_id'), table_name='shift_change_requests')
    op.drop_table('shift_change_requests')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_table('attendances')
    op.alter_column('job_postings', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('job_postings', 'number_of_positions',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('job_postings', 'employment_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('job_postings', 'location',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('job_postings', 'salary',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('job_postings', 'posting_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('job_postings', 'closing_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('job_postings', 'description_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('job_postings', 'created_by_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('job_postings_ibfk_1'), 'job_postings', type_='foreignkey')
    op.drop_constraint(op.f('job_postings_ibfk_2'), 'job_postings', type_='foreignkey')
    op.create_foreign_key(None, 'job_postings', 'roles', ['role_id'], ['id'])
    op.add_column('leave_master', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('leave_master', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('leave_master', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('leave_master', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_column('leave_master', 'start_date')
    op.drop_column('leave_master', 'leave_type')
    op.drop_column('leave_master', 'end_date')
    op.drop_constraint(op.f('quiz_checkpoints_ibfk_2'), 'quiz_checkpoints', type_='foreignkey')
    op.drop_column('quiz_checkpoints', 'course_id')
    op.add_column('shifts', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('shifts', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('shifts', sa.Column('shift_name', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'shifts', ['name'])
    op.drop_column('shifts', 'is_rotational')
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False))
    op.drop_index(op.f('biometric_id'), table_name='users')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'biometric_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('biometric_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False))
    op.create_index(op.f('biometric_id'), 'users', ['biometric_id'], unique=True)
    op.drop_column('users', 'name')
    op.add_column('shifts', sa.Column('is_rotational', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shifts', type_='unique')
    op.drop_column('shifts', 'shift_name')
    op.drop_column('shifts', 'description')
    op.drop_column('shifts', 'name')
    op.add_column('quiz_checkpoints', sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('quiz_checkpoints_ibfk_2'), 'quiz_checkpoints', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.add_column('leave_master', sa.Column('end_date', sa.DATE(), nullable=False))
    op.add_column('leave_master', sa.Column('leave_type', mysql.ENUM('CASUAL', 'SICK', 'EARNED', 'MATERNITY', 'BEREAVEMENT', 'STUDY', 'SPECIAL', 'UNPAID', 'PUBLIC_HOLIDAY', 'COMP_OFF'), nullable=False))
    op.add_column('leave_master', sa.Column('start_date', sa.DATE(), nullable=False))
    op.drop_column('leave_master', 'year')
    op.drop_column('leave_master', 'date')
    op.drop_column('leave_master', 'status')
    op.drop_column('leave_master', 'name')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.create_foreign_key(op.f('job_postings_ibfk_2'), 'job_postings', 'job_roles', ['description_id'], ['id'])
    op.create_foreign_key(op.f('job_postings_ibfk_1'), 'job_postings', 'job_roles', ['role_id'], ['id'])
    op.alter_column('job_postings', 'created_by_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('job_postings', 'description_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('job_postings', 'closing_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('job_postings', 'posting_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('job_postings', 'salary',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('job_postings', 'location',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('job_postings', 'employment_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('job_postings', 'number_of_positions',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('job_postings', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_table('attendances',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('punch_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('latitude', mysql.FLOAT(), nullable=True),
    sa.Column('longitude', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('first_punch', mysql.DATETIME(), nullable=True),
    sa.Column('last_punch', mysql.DATETIME(), nullable=True),
    sa.Column('shift_start', mysql.DATETIME(), nullable=True),
    sa.Column('shift_end', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('attendances_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.create_table('shift_change_requests',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_shift_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_shift_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('request_date', sa.DATE(), nullable=True),
    sa.Column('reason', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Pending'"), nullable=True),
    sa.ForeignKeyConstraint(['new_shift_id'], ['shifts.id'], name=op.f('shift_change_requests_ibfk_3')),
    sa.ForeignKeyConstraint(['old_shift_id'], ['shifts.id'], name=op.f('shift_change_requests_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('shift_change_requests_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_shift_change_requests_id'), 'shift_change_requests', ['id'], unique=False)
    op.create_table('candidate_documents',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('document_url', mysql.VARCHAR(length=500), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('candidate_documents_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_candidate_documents_id'), 'candidate_documents', ['id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('applied_date', sa.DATE(), nullable=False),
    sa.Column('resume_url', mysql.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('candidates_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.create_index(op.f('email'), 'candidates', ['email'], unique=True)
    op.create_table('workflows',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('approval_required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('approver_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approval_status', mysql.ENUM('Pending', 'Approved', 'Rejected'), nullable=True),
    sa.Column('posting_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], name=op.f('workflows_ibfk_2')),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], name=op.f('workflows_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_workflows_id'), 'workflows', ['id'], unique=False)
    op.create_table('user_shifts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shift_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_date', sa.DATE(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name=op.f('user_shifts_ibfk_2')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_shifts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_shifts_id'), 'user_shifts', ['id'], unique=False)
    op.create_table('job_roles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('required_skills', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('title'), 'job_roles', ['title'], unique=True)
    op.create_index(op.f('ix_job_roles_id'), 'job_roles', ['id'], unique=False)
    # ### end Alembic commands ###
