"""create shift table

Revision ID: 9cdb81764562
Revises: b7d257e37d55
Create Date: 2025-09-24 17:56:57.930745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9cdb81764562'
down_revision: Union[str, Sequence[str], None] = 'b7d257e37d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'photo',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.LargeBinary(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'photo',
               existing_type=sa.LargeBinary(),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
