"""Add subscription id to the organization model

Revision ID: a619dd80bfed
Revises: 8256e5302656
Create Date: 2025-11-28 12:08:07.600981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a619dd80bfed'
down_revision: Union[str, Sequence[str], None] = '8256e5302656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('subscription_status', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('subscription_start_date', sa.Date(), nullable=True))
    op.add_column('organizations', sa.Column('subscription_end_date', sa.Date(), nullable=True))
    op.add_column('organizations', sa.Column('branch_limit', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('current_branches', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('user_limit', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('current_users', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('storage_limit_mb', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('current_storage_mb', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('last_payment_date', sa.Date(), nullable=True))
    op.add_column('organizations', sa.Column('next_billing_date', sa.Date(), nullable=True))
    op.add_column('organizations', sa.Column('total_amount_paid', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('organizations', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('organizations', sa.Column('contact_email', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('contact_phone', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('modified_by', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'organizations', 'subscription_plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'modified_by')
    op.drop_column('organizations', 'created_by')
    op.drop_column('organizations', 'contact_phone')
    op.drop_column('organizations', 'contact_email')
    op.drop_column('organizations', 'is_active')
    op.drop_column('organizations', 'total_amount_paid')
    op.drop_column('organizations', 'next_billing_date')
    op.drop_column('organizations', 'last_payment_date')
    op.drop_column('organizations', 'current_storage_mb')
    op.drop_column('organizations', 'storage_limit_mb')
    op.drop_column('organizations', 'current_users')
    op.drop_column('organizations', 'user_limit')
    op.drop_column('organizations', 'current_branches')
    op.drop_column('organizations', 'branch_limit')
    op.drop_column('organizations', 'subscription_end_date')
    op.drop_column('organizations', 'subscription_start_date')
    op.drop_column('organizations', 'subscription_status')
    op.drop_column('organizations', 'plan_id')
    # ### end Alembic commands ###
