"""add branch_id to job_postings

Revision ID: af5c675b8756
Revises: 848391537544
Create Date: 2025-12-19 19:21:15.479179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af5c675b8756'
down_revision: Union[str, Sequence[str], None] = '848391537544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('branch_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'job_postings', 'branches', ['branch_id'], ['id'])
    op.alter_column('test_reports', 'failures',
               existing_type=mysql.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('test_reports', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.create_index(op.f('ix_test_reports_id'), 'test_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_reports_id'), table_name='test_reports')
    op.alter_column('test_reports', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('test_reports', 'failures',
               existing_type=sa.JSON(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_column('job_postings', 'branch_id')
    # ### end Alembic commands ###
