"""modified attendance table

Revision ID: b098e3f1926d
Revises: 892ac80f3288
Create Date: 2025-11-20 11:50:53.297475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b098e3f1926d'
down_revision: Union[str, Sequence[str], None] = '892ac80f3288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendances', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('attendances', sa.Column('modified_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'modified_by')
    op.drop_column('attendances', 'created_by')
    op.drop_column('attendances', 'updated_at')
    # ### end Alembic commands ###
