"""Add choices and correct_answer to quiz_checkpoints

Revision ID: b0aa6bb54999
Revises: 3cf1aaa5469a
Create Date: 2025-09-10 12:16:09.753688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b0aa6bb54999'
down_revision: Union[str, Sequence[str], None] = '3cf1aaa5469a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'duration',
               existing_type=mysql.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('quiz_checkpoints', sa.Column('choices', sa.String(length=500), nullable=False))
    op.add_column('quiz_checkpoints', sa.Column('correct_answer', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_checkpoints', 'correct_answer')
    op.drop_column('quiz_checkpoints', 'choices')
    op.alter_column('courses', 'duration',
               existing_type=sa.Float(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
