"""add organization_logo to orgnizations table

Revision ID: b16e987e9f2b
Revises: 7de48520aeb8
Create Date: 2025-11-28 16:33:41.319540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16e987e9f2b'
down_revision: Union[str, Sequence[str], None] = '7de48520aeb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('Organization_logo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'Organization_logo')
    # ### end Alembic commands ###
