"""Added salary structure and payroll tables

Revision ID: b1865ac8155a
Revises: bcdde37913f4
Create Date: 2025-10-09 13:10:28.192653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1865ac8155a'
down_revision: Union[str, Sequence[str], None] = 'bcdde37913f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payrolls', sa.Column('salary_structure_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payrolls', 'salary_structures', ['salary_structure_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payrolls', type_='foreignkey')
    op.drop_column('payrolls', 'salary_structure_id')
    # ### end Alembic commands ###
