"""Fix JobRole, JobPosting, Workflow relationships

Revision ID: b3f421f8cf3a
Revises: bfc7b0dbaceb
Create Date: 2025-10-09 12:17:54.129144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f421f8cf3a'
down_revision: Union[str, Sequence[str], None] = 'bfc7b0dbaceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('job_postings_ibfk_1'), 'job_postings', type_='foreignkey')
    op.create_foreign_key(None, 'job_postings', 'job_roles', ['role_id'], ['id'])
    op.add_column('leave_master', sa.Column('leave_date', sa.Date(), nullable=False))
    op.drop_column('leave_master', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leave_master', sa.Column('date', sa.DATE(), nullable=False))
    op.drop_column('leave_master', 'leave_date')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.create_foreign_key(op.f('job_postings_ibfk_1'), 'job_postings', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
