"""modified user shifts 

Revision ID: b70718047e0b
Revises: be14e2c9b997
Create Date: 2025-11-20 13:24:16.566190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b70718047e0b'
down_revision: Union[str, Sequence[str], None] = 'be14e2c9b997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_shifts', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('user_shifts', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_shifts', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('user_shifts', sa.Column('modified_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_shifts', 'modified_by')
    op.drop_column('user_shifts', 'created_by')
    op.drop_column('user_shifts', 'updated_at')
    op.drop_column('user_shifts', 'created_at')
    # ### end Alembic commands ###
