"""create shift table

Revision ID: bb595cdd6d16
Revises: 9cdb81764562
Create Date: 2025-09-24 22:13:43.885572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb595cdd6d16'
down_revision: Union[str, Sequence[str], None] = '9cdb81764562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
