"""update salary_structure to annual

Revision ID: bcdde37913f4
Revises: c73c78d21b76
Create Date: 2025-10-08 17:26:01.302479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bcdde37913f4'
down_revision: Union[str, Sequence[str], None] = 'c73c78d21b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leave_master', 'holiday',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('leave_master', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.add_column('salary_structures', sa.Column('basic_salary_annual', sa.Float(), nullable=False))
    op.add_column('salary_structures', sa.Column('allowances_annual', sa.Float(), nullable=True))
    op.add_column('salary_structures', sa.Column('deductions_annual', sa.Float(), nullable=True))
    op.add_column('salary_structures', sa.Column('bonus_annual', sa.Float(), nullable=True))
    op.add_column('salary_structures', sa.Column('total_annual', sa.Float(), nullable=True))
    op.drop_column('salary_structures', 'basic_salary')
    op.drop_column('salary_structures', 'allowances')
    op.drop_column('salary_structures', 'deductions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_structures', sa.Column('deductions', mysql.FLOAT(), nullable=True))
    op.add_column('salary_structures', sa.Column('allowances', mysql.FLOAT(), nullable=True))
    op.add_column('salary_structures', sa.Column('basic_salary', mysql.FLOAT(), nullable=False))
    op.drop_column('salary_structures', 'total_annual')
    op.drop_column('salary_structures', 'bonus_annual')
    op.drop_column('salary_structures', 'deductions_annual')
    op.drop_column('salary_structures', 'allowances_annual')
    op.drop_column('salary_structures', 'basic_salary_annual')
    op.alter_column('leave_master', 'status',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('leave_master', 'holiday',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###
