"""update shift change request 

Revision ID: be14e2c9b997
Revises: 02e19aa9cae8
Create Date: 2025-11-20 12:56:53.789563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be14e2c9b997'
down_revision: Union[str, Sequence[str], None] = '02e19aa9cae8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shift_change_requests', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('shift_change_requests', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shift_change_requests', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('shift_change_requests', sa.Column('modified_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shift_change_requests', 'modified_by')
    op.drop_column('shift_change_requests', 'created_by')
    op.drop_column('shift_change_requests', 'updated_at')
    op.drop_column('shift_change_requests', 'created_at')
    # ### end Alembic commands ###
