"""create a job_role table

Revision ID: bfc7b0dbaceb
Revises: f7582eab9233
Create Date: 2025-10-09 10:52:54.561124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bfc7b0dbaceb'
down_revision: Union[str, Sequence[str], None] = 'f7582eab9233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(op.f('job_postings_ibfk_2'), 'job_postings', type_='foreignkey')
    # op.drop_column('job_postings', 'workflow_id')
    op.alter_column('leave_master', 'date',
              existing_type=sa.DATE(),
             nullable=False)
    op.drop_column('leave_master', 'status')
    op.add_column('workflows', sa.Column('job_posting_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('workflows_ibfk_1'), 'workflows', type_='foreignkey')
    op.create_foreign_key(None, 'workflows', 'job_postings', ['job_posting_id'], ['id'])
    op.drop_column('workflows', 'job_postings_id')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('job_postings_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.create_foreign_key(op.f('workflows_ibfk_1'), 'workflows', 'job_postings', ['job_postings_id'], ['id'])
    op.drop_column('workflows', 'job_posting_id')
    op.add_column('leave_master', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.alter_column('leave_master', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.add_column('job_postings', sa.Column('workflow_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('job_postings_ibfk_2'), 'job_postings', 'workflows', ['workflow_id'], ['id'])
    # ### end Alembic commands ###
