"""Add question column to quiz_checkpoints

Revision ID: c7a0af826fdd
Revises: 009d55d2ebca
Create Date: 2025-09-09 17:07:30.268888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c7a0af826fdd'
down_revision: Union[str, Sequence[str], None] = '009d55d2ebca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_checkpoints', sa.Column('question', sa.String(length=500), nullable=False))
    op.drop_column('quiz_checkpoints', 'required')
    op.add_column('quiz_histories', sa.Column('answer', sa.String(length=500), nullable=False))
    op.add_column('quiz_histories', sa.Column('result', sa.String(length=50), nullable=False))
    op.drop_column('quiz_histories', 'score')
    op.drop_column('quiz_histories', 'completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_histories', sa.Column('completed_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('quiz_histories', sa.Column('score', mysql.FLOAT(), nullable=True))
    op.drop_column('quiz_histories', 'result')
    op.drop_column('quiz_histories', 'answer')
    op.add_column('quiz_checkpoints', sa.Column('required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('quiz_checkpoints', 'question')
    # ### end Alembic commands ###
