"""your migration message

Revision ID: d07f09161d8c
Revises: 4d43f29c963c
Create Date: 2025-11-09 19:35:06.617667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd07f09161d8c'
down_revision: Union[str, Sequence[str], None] = '4d43f29c963c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_shifts_id'), 'user_shifts', ['id'], unique=False)
    op.add_column('attendances', sa.Column('shift_id', sa.Integer(), nullable=False))
    op.add_column('attendances', sa.Column('attendance_date', sa.Date(), nullable=False))
    op.add_column('attendances', sa.Column('punch_in', sa.DateTime(), nullable=False))
    op.add_column('attendances', sa.Column('punch_out', sa.DateTime(), nullable=False))
    op.add_column('attendances', sa.Column('total_worked_minutes', sa.Integer(), nullable=True))
    op.alter_column('attendances', 'status',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.create_foreign_key(None, 'attendances', 'shifts', ['shift_id'], ['id'])
    op.drop_column('attendances', 'shift_end')
    op.drop_column('attendances', 'punch_id')
    op.drop_column('attendances', 'latitude')
    op.drop_column('attendances', 'shift_start')
    op.drop_column('attendances', 'longitude')
    op.drop_column('attendances', 'updated_at')
    op.drop_column('attendances', 'first_punch')
    op.drop_column('attendances', 'last_punch')
    op.create_index(op.f('ix_candidate_documents_id'), 'candidate_documents', ['id'], unique=False)
    op.create_foreign_key(None, 'candidate_documents', 'candidates', ['candidate_id'], ['id'])
    op.add_column('candidates', sa.Column('workflow_id', sa.Integer(), nullable=False))
    op.add_column('candidates', sa.Column('applied_date', sa.Date(), nullable=False))
    op.alter_column('candidates', 'email',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.create_foreign_key(None, 'candidates', 'workflows', ['workflow_id'], ['id'])
    op.drop_column('candidates', 'created_at')
    op.create_index(op.f('ix_job_postings_id'), 'job_postings', ['id'], unique=False)
    op.drop_column('job_postings', 'description')
    op.drop_column('job_postings', 'title')
    op.add_column('leave_master', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('leave_master', sa.Column('end_date', sa.Date(), nullable=True))
    op.drop_column('leave_master', 'status')
    op.drop_column('leave_master', 'name')
    op.drop_column('leave_master', 'year')
    op.drop_column('leave_master', 'date')
    op.add_column('quiz_checkpoints', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quiz_checkpoints', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.alter_column('shifts', 'start_time',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('shifts', 'end_time',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('shifts', 'shift_code',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.add_column('users', sa.Column('first_name', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('biometric_id', sa.String(length=50), nullable=True))
    op.drop_constraint(op.f('users_ibfk_3'), 'users', type_='foreignkey')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.create_foreign_key(op.f('users_ibfk_3'), 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'biometric_id')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.alter_column('shifts', 'shift_code',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('shifts', 'end_time',
               existing_type=sa.Time(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('shifts', 'start_time',
               existing_type=sa.Time(),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_constraint(None, 'quiz_checkpoints', type_='foreignkey')
    op.drop_column('quiz_checkpoints', 'course_id')
    op.add_column('leave_master', sa.Column('date', sa.DATE(), nullable=True))
    op.add_column('leave_master', sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leave_master', sa.Column('name', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('leave_master', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('leave_master', 'end_date')
    op.drop_column('leave_master', 'start_date')
    op.add_column('job_postings', sa.Column('title', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('job_postings', sa.Column('description', mysql.TEXT(), nullable=True))
    op.drop_index(op.f('ix_job_postings_id'), table_name='job_postings')
    op.add_column('candidates', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.alter_column('candidates', 'email',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('candidates', 'applied_date')
    op.drop_column('candidates', 'workflow_id')
    op.drop_constraint(None, 'candidate_documents', type_='foreignkey')
    op.drop_index(op.f('ix_candidate_documents_id'), table_name='candidate_documents')
    op.add_column('attendances', sa.Column('last_punch', mysql.DATETIME(), nullable=True))
    op.add_column('attendances', sa.Column('first_punch', mysql.DATETIME(), nullable=True))
    op.add_column('attendances', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))
    op.add_column('attendances', sa.Column('longitude', mysql.FLOAT(), nullable=True))
    op.add_column('attendances', sa.Column('shift_start', mysql.DATETIME(), nullable=True))
    op.add_column('attendances', sa.Column('latitude', mysql.FLOAT(), nullable=True))
    op.add_column('attendances', sa.Column('punch_id', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('attendances', sa.Column('shift_end', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.alter_column('attendances', 'status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('attendances', 'total_worked_minutes')
    op.drop_column('attendances', 'punch_out')
    op.drop_column('attendances', 'punch_in')
    op.drop_column('attendances', 'attendance_date')
    op.drop_column('attendances', 'shift_id')
    op.drop_index(op.f('ix_user_shifts_id'), table_name='user_shifts')
    op.drop_table('user_shifts')
    # ### end Alembic commands ###
