"""Make role_id nullable and adjust user model

Revision ID: d1bb563c67f6
Revises: 7ec27f156e30
Create Date: 2025-09-10 15:13:09.536310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd1bb563c67f6'
down_revision: Union[str, Sequence[str], None] = '7ec27f156e30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
