"""adding extra fields to role table

Revision ID: d9b977eb5e42
Revises: 25c8d4d48431
Create Date: 2025-09-25 12:11:14.654261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd9b977eb5e42'
down_revision: Union[str, Sequence[str], None] = '25c8d4d48431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('code', sa.String(length=20), nullable=False))
    op.add_column('roles', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Text(), nullable=True))
    op.add_column('roles', sa.Column('status', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.create_unique_constraint(None, 'roles', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'status')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'description')
    op.drop_column('roles', 'code')
    # ### end Alembic commands ###
