"""update payroll add audit fields

Revision ID: da2dc319f17c
Revises: f3d652600c37
Create Date: 2025-11-21 14:09:10.023849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da2dc319f17c'
down_revision: Union[str, Sequence[str], None] = 'f3d652600c37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payrolls', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('payrolls', sa.Column('modified_by', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payrolls', 'modified_by')
    op.drop_column('payrolls', 'created_by')
    # ### end Alembic commands ###
