"""remove organization_url to orgnizations table

Revision ID: df03ecb118cf
Revises: b16e987e9f2b
Create Date: 2025-11-28 17:14:17.396974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'df03ecb118cf'
down_revision: Union[str, Sequence[str], None] = 'b16e987e9f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('Organization_logo', sa.String(length=255), nullable=True))
    op.drop_column('organizations', 'Organization_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('Organization_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('organizations', 'Organization_logo')
    # ### end Alembic commands ###
