"""add shift_name and shift_type columns

Revision ID: df498f9d4cd1
Revises: 57187500bb55
Create Date: 2025-11-12 11:16:23.379049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'df498f9d4cd1'
down_revision: Union[str, Sequence[str], None] = '57187500bb55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('shift_type', sa.String(length=50), nullable=True))
    op.drop_index(op.f('name'), table_name='shifts')
    op.drop_index(op.f('name_2'), table_name='shifts')
    op.drop_index(op.f('uq_shifts_name'), table_name='shifts')
    op.create_unique_constraint(None, 'shifts', ['shift_name'])
    op.drop_column('shifts', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'shifts', type_='unique')
    op.create_index(op.f('uq_shifts_name'), 'shifts', ['name'], unique=True)
    op.create_index(op.f('name_2'), 'shifts', ['name'], unique=True)
    op.create_index(op.f('name'), 'shifts', ['name'], unique=True)
    op.drop_column('shifts', 'shift_type')
    # ### end Alembic commands ###
