"""added is_week_off & updated shift model

Revision ID: e166cc2c3bdb
Revises: e88d8b1a2d3e
Create Date: 2025-11-24 15:13:05.352407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e166cc2c3bdb'
down_revision: Union[str, Sequence[str], None] = 'e88d8b1a2d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shifts', sa.Column('is_week_off', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'is_week_off')
    # ### end Alembic commands ###
