"""create a shift_roaster_detail table

Revision ID: e3231ecfc494
Revises: 5c1c56761ecd
Create Date: 2025-11-08 23:47:04.849805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3231ecfc494'
down_revision: Union[str, Sequence[str], None] = '5c1c56761ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_shifts', 'shift_roster_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('fk_user_shifts_shift_roster_id'), 'user_shifts', type_='foreignkey')
    op.create_foreign_key(None, 'user_shifts', 'shift_rosters', ['shift_roster_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_shifts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_shifts_shift_roster_id'), 'user_shifts', 'shift_rosters', ['shift_roster_id'], ['id'], ondelete='SET NULL')
    op.alter_column('user_shifts', 'shift_roster_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
