"""add required column to quiz_checkpoints

Revision ID: e641630bcf5c
Revises: c7a0af826fdd
Create Date: 2025-09-09 17:14:21.232835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e641630bcf5c'
down_revision: Union[str, Sequence[str], None] = 'c7a0af826fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_checkpoints', sa.Column('required', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_checkpoints', 'required')
    # ### end Alembic commands ###
