"""Add Shift-UserShift relationship

Revision ID: e98879d4900d
Revises: a32d3ba3ee4e
Create Date: 2025-10-30 11:11:50.567706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98879d4900d'
down_revision: Union[str, Sequence[str], None] = 'a32d3ba3ee4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
