"""add course_id to quiz_checkpoints

Revision ID: ea07d98b8829
Revises: 1780098328a8
Create Date: 2025-09-25 11:04:45.964705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea07d98b8829'
down_revision: Union[str, Sequence[str], None] = '1780098328a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_checkpoints', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quiz_checkpoints', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.add_column('quiz_histories', sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_histories', 'completed_at')
    op.drop_constraint(None, 'quiz_checkpoints', type_='foreignkey')
    op.drop_column('quiz_checkpoints', 'course_id')
    # ### end Alembic commands ###
