"""Add question column to quiz_histories

Revision ID: f3b49cbd1504
Revises: d1bb563c67f6
Create Date: 2025-09-11 11:40:53.903273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b49cbd1504'
down_revision: Union[str, Sequence[str], None] = 'd1bb563c67f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_histories', sa.Column('question', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_histories', 'question')
    # ### end Alembic commands ###
