"""Add organization_id and branch_id to users

Revision ID: f3d55ffd4ba9
Revises: c642d708939b
Create Date: 2025-10-04 16:55:01.371578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3d55ffd4ba9'
down_revision: Union[str, Sequence[str], None] = 'c642d708939b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'courses', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.alter_column('videos', 'title',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('videos', 'duration',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'duration',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('videos', 'title',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'category_id')
    op.drop_column('courses', 'organization_id')
    # ### end Alembic commands ###
