"""Update salary structure remove user_id add audit fields

Revision ID: f3d652600c37
Revises: 22e78e4be3b9
Create Date: 2025-11-21 12:53:00.150539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3d652600c37'
down_revision: Union[str, Sequence[str], None] = '22e78e4be3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_structures', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('salary_structures', sa.Column('modified_by', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('salary_structures_ibfk_1'), 'salary_structures', type_='foreignkey')
    op.drop_column('salary_structures', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary_structures', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('salary_structures_ibfk_1'), 'salary_structures', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('salary_structures', 'modified_by')
    op.drop_column('salary_structures', 'created_by')
    # ### end Alembic commands ###
