"""Fix workflow relationship

Revision ID: f83a205910c7
Revises: b3f421f8cf3a
Create Date: 2025-10-10 11:13:25.255906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f83a205910c7'
down_revision: Union[str, Sequence[str], None] = 'b3f421f8cf3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'description_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'job_postings', 'job_roles', ['description_id'], ['id'])
    op.add_column('workflows', sa.Column('posting_id', sa.Integer(), nullable=False))
    op.alter_column('workflows', 'approval_status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('Pending', 'Approved', 'Rejected', name='approvalstatus'),
               existing_nullable=True)
    op.drop_constraint(op.f('workflows_ibfk_1'), 'workflows', type_='foreignkey')
    op.create_foreign_key(None, 'workflows', 'job_postings', ['posting_id'], ['id'])
    op.create_foreign_key(None, 'workflows', 'users', ['approver_id'], ['id'])
    op.drop_column('workflows', 'created_by')
    op.drop_column('workflows', 'job_posting_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('job_posting_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('workflows', sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.create_foreign_key(op.f('workflows_ibfk_1'), 'workflows', 'job_postings', ['job_posting_id'], ['id'])
    op.alter_column('workflows', 'approval_status',
               existing_type=sa.Enum('Pending', 'Approved', 'Rejected', name='approvalstatus'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('workflows', 'posting_id')
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.alter_column('job_postings', 'description_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
