"""Make job_posting_id nullable

Revision ID: f98bf098077b
Revises: 7de48520aeb8
Create Date: 2025-12-04 13:51:12.595069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f98bf098077b'
down_revision: Union[str, Sequence[str], None] = '7de48520aeb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'job_posting_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'job_posting_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
