from app.models.user_m import User
from app.models.role_m import Role
from app.models.course_m import Course
from app.models.video_m import Video
from app.models.QuizCheckpoint_m import QuizCheckpoint
from app.models.QuizHistory_m import QuizHistory
from app.models.Progress_m import Progress
from app.models.organization_m import *
from app.models.branch_m import Branch
from app.models.category_m import Category
from app.models.salary_structure_m import SalaryStructure
from app.models.payroll_m import Payroll
from app.models.formula_m import Formula
from app.models.permission_m import Permission
from app.models.attendance_m import Attendance
from app.models.payroll_attendance_m import PayrollAttendance
from app.models.candidate_documents_m import CandidateDocument
from app.models.candidate_m import Candidate
from app.models.job_posting_m import JobPosting
from app.models.jobrole_m import JobRole
from app.models.leavemaster_m import LeaveMaster
from app.models.shift_change_request_m import ShiftChangeRequest
from app.models.user_shifts_m import UserShift
from app.models.workflow_m import Workflow