from app.models.user_m import *
from app.models.role_m import *
from app.models.course_m import *
from app.models.video_m import *
from app.models.QuizCheckpoint_m import *
from app.models.QuizHistory_m import *
from app.models.Progress_m import *
from app.models.enrollment_m import *
from app.models.organization import *
from app.models.branch_m import *